### ISSUE TITLE
Truncated at direction change point in KinoAstar::searchTime()

### ISSUE THREAD

**Issue by Chortine** [ZJU-FAST-Lab/Car-like-Robotic-swarm#8]
https://github.com/ZJU-FAST-Lab/Car-like-Robotic-swarm/blob/eabbf7c907babe450b49da88c204bf61bf6c1709/src/Minco/traj_planner/src/kino_astar.cpp#L919C21-L919C21

![image](https://github.com/ZJU-FAST-Lab/Car-like-Robotic-swarm/assets/107395103/166cfaca-6415-40cc-9985-ca565ff360f1)

Hi team,

When before doing the st-graph search, why the ego-trajectory is truncated at the direction change point? Means that only the first segment of the traj. is considered, when there is a backward segment afterwards, it is ignore.

Shouldn't we instead consider the full predicted trajectory when we do the dynamic obstacle avoidance?

Thank you very much.

**Comment by Leon-Redfield** [comment]
Hi! Thank you for your question. The truncated point is used to separate the trajectory into segments, where each segment represents a direction of moving forward or backward. And you are right, I only considered the first segment where the car is moving forward, and ignored the backward case. Because in an early version of the MPC code, the controller could not accurately follow the trajectory when the car is moving backward, so I only preserved the first segment. If you're interested, you are encouraged to add the backward case by yourself, thanks and good luck!
