### ISSUE TITLE
Hello, I want to modify on the basis of your code, and I want to add priority planning. Which part should I modify specifically? Look forward to your reply, thank you very much!

### ISSUE THREAD

**Issue by 3oo0q-kvmlskz** [ZJU-FAST-Lab/Car-like-Robotic-swarm#9]
Hello, I want to modify on the basis of your code, and I want to add priority planning. Which part should I modify specifically? Look forward to your reply, thank you very much!

**Comment by Leon-Redfield** [comment]
Well this problem is a little bit complicated. If you want to modify the code into the priority planning mode, you first need to define the priority of each robot in the swarm. And then, while planning, each robot should wait until the higher priority robot finishes planning and broadcast trajectories. After that, the planning part is similar, there's not much to change. Therefore, the main part you need to focus on is the code logic and priority logic. Good luck.
